"""Simplified coagulation cascade ODE model.

Simplified from Hockin et al. (2002) 34-species model to an 8-state reduced system
that captures the key dynamics of hemostasis for reinforcement learning applications.

States:
    0: TF_VIIa     - Tissue Factor / Factor VIIa complex (nM)
    1: Xa           - Activated Factor X (nM)
    2: Va           - Activated Factor V (nM)
    3: IIa          - Thrombin (activated Factor II) (nM)
    4: fibrinogen   - Fibrinogen concentration (mg/dL)
    5: fibrin       - Fibrin concentration (mg/dL)
    6: AT_III_bound - Antithrombin III-bound complexes (nM)
    7: platelet_act - Activated platelet fraction (0-1)

Reference:
    Hockin MF, Jones KC, Everse SJ, Mann KG. A model for the stoichiometric
    regulation of blood coagulation. J Biol Chem. 2002;277(21):18322-18333.
"""

from __future__ import annotations

import numpy as np
from scipy.integrate import solve_ivp


# Default physiological parameters for the reduced cascade model
DEFAULT_PARAMS = {
    # TF initiation rates
    "k_tf_viia_formation": 0.5,       # nM/min - TF:VIIa complex formation rate
    "k_tf_viia_decay": 0.05,          # 1/min  - TF:VIIa complex decay

    # Factor X activation by TF:VIIa
    "k_xa_formation": 0.2,            # 1/min  - Xa generation from TF:VIIa
    "k_xa_decay": 0.01,               # 1/min  - Xa natural decay

    # Factor V activation by thrombin (positive feedback)
    "k_va_formation": 0.3,            # 1/(nM*min) - Va activation by thrombin
    "k_va_decay": 0.02,               # 1/min      - Va decay

    # Prothrombinase complex (Xa:Va) -> Thrombin generation
    "k_thrombin_gen": 1.0,            # 1/(nM*min) - thrombin generation rate
    "k_thrombin_decay": 0.05,         # 1/min      - thrombin natural decay
    "prothrombin_conc": 1400.0,       # nM         - prothrombin pool

    # Fibrin formation
    "k_fibrin_formation": 0.1,        # 1/(nM*min) - fibrinogen->fibrin by thrombin
    "baseline_fibrinogen": 300.0,     # mg/dL      - normal fibrinogen

    # Antithrombin III inhibition
    "k_at3_binding": 0.02,            # 1/(nM*min) - AT-III binding rate
    "at3_total": 3000.0,              # nM         - total AT-III pool

    # Platelet activation by thrombin
    "k_platelet_activation": 0.05,    # 1/(nM*min)
    "k_platelet_deactivation": 0.005, # 1/min

    # INR / aPTT model parameters
    "normal_pt_seconds": 12.0,        # seconds - normal prothrombin time
    "normal_aptt_seconds": 30.0,      # seconds - normal aPTT
    "isi": 1.0,                       # International Sensitivity Index
}


class CoagulationCascade:
    """Simplified 8-state coagulation cascade ODE model.

    Reduced from the full Hockin-Mann 34-species model to capture
    key dynamics relevant for anticoagulation therapy simulation.
    """

    N_STATES = 8

    def __init__(self, params: dict | None = None) -> None:
        self.params = {**DEFAULT_PARAMS}
        if params is not None:
            self.params.update(params)

    def _derivatives(self, t: float, y: np.ndarray) -> np.ndarray:
        """ODE right-hand side for the reduced coagulation cascade."""
        p = self.params

        # Unpack state - clamp negatives to zero for numerical stability
        tf_viia = max(y[0], 0.0)
        xa = max(y[1], 0.0)
        va = max(y[2], 0.0)
        iia = max(y[3], 0.0)  # thrombin
        fibrinogen = max(y[4], 0.0)
        at3_bound = max(y[6], 0.0)
        platelet_act = np.clip(y[7], 0.0, 1.0)

        # Free AT-III available for binding
        at3_free = max(p["at3_total"] - at3_bound, 0.0)

        # Available prothrombin (depleted by thrombin generation)
        prothrombin_available = max(p["prothrombin_conc"] - iia - at3_bound * 0.5, 0.0)

        dydt = np.zeros(8)

        # 0: TF:VIIa complex - tissue factor initiation pathway
        # Simplified from Hockin et al. (2002) 34-ODE model
        dydt[0] = p["k_tf_viia_formation"] - p["k_tf_viia_decay"] * tf_viia

        # 1: Factor Xa - generated by TF:VIIa, inhibited by AT-III
        dydt[1] = (
            p["k_xa_formation"] * tf_viia
            - p["k_xa_decay"] * xa
            - p["k_at3_binding"] * xa * at3_free * 0.3  # AT-III inhibits Xa
        )

        # 2: Factor Va - activated by thrombin (positive feedback loop)
        # Also small direct activation by Xa to bootstrap the cascade
        # (physiologically, trace thrombin from initial Xa activates Va)
        dydt[2] = (
            p["k_va_formation"] * (iia + 0.01 * xa) * (1.0 - va / 100.0)
            - p["k_va_decay"] * va
        )

        # 3: Thrombin (IIa) - generated by prothrombinase (Xa:Va), inhibited by AT-III
        # Also small direct generation from Xa alone (initial phase)
        prothrombinase_activity = xa * va / (1.0 + xa + va)  # Michaelis-Menten-like
        direct_xa_thrombin = 0.005 * xa  # trace thrombin from Xa before amplification
        dydt[3] = (
            p["k_thrombin_gen"] * prothrombinase_activity
            * prothrombin_available / (prothrombin_available + 500.0)
            + direct_xa_thrombin
            - p["k_thrombin_decay"] * iia
            - p["k_at3_binding"] * iia * at3_free  # AT-III is primary thrombin inhibitor
        )

        # 4: Fibrinogen - consumed by thrombin to form fibrin
        dydt[4] = -p["k_fibrin_formation"] * iia * fibrinogen / (fibrinogen + 50.0)

        # 5: Fibrin - formed from fibrinogen by thrombin
        dydt[5] = p["k_fibrin_formation"] * iia * fibrinogen / (fibrinogen + 50.0)

        # 6: AT-III bound complexes - accumulate as AT-III binds thrombin and Xa
        dydt[6] = (
            p["k_at3_binding"] * iia * at3_free
            + p["k_at3_binding"] * xa * at3_free * 0.3
        )

        # 7: Platelet activation fraction - activated by thrombin
        dydt[7] = (
            p["k_platelet_activation"] * iia * (1.0 - platelet_act)
            - p["k_platelet_deactivation"] * platelet_act
        )

        return dydt

    def simulate(
        self,
        initial_state: np.ndarray,
        t_span: tuple[float, float],
        dt: float = 0.1,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Solve the coagulation cascade ODEs.

        Args:
            initial_state: 8-element state vector.
            t_span: (t_start, t_end) in minutes.
            dt: Output time step in minutes.

        Returns:
            (times, states) where states has shape (n_times, 8).
        """
        if len(initial_state) != self.N_STATES:
            raise ValueError(f"initial_state must have {self.N_STATES} elements")

        t_eval = np.arange(t_span[0], t_span[1] + dt * 0.5, dt)

        sol = solve_ivp(
            self._derivatives,
            t_span,
            initial_state,
            method="RK45",
            t_eval=t_eval,
            rtol=1e-6,
            atol=1e-9,
            max_step=dt,
        )

        if not sol.success:
            raise RuntimeError(f"ODE solver failed: {sol.message}")

        # Clamp negative concentrations to zero
        states = np.maximum(sol.y.T, 0.0)
        # Clamp platelet activation to [0, 1]
        states[:, 7] = np.clip(states[:, 7], 0.0, 1.0)

        return sol.t, states

    def get_inr(self, state: np.ndarray) -> float:
        """Calculate INR from the current coagulation state.

        INR is derived from the ratio of patient prothrombin time to normal,
        raised to the power of the ISI. Here we model PT as inversely related
        to functional prothrombin / thrombin generation capacity.
        """
        p = self.params
        iia = max(state[3], 0.0)  # thrombin
        xa = max(state[1], 0.0)

        # Higher thrombin generation capacity -> shorter PT -> lower INR
        # Normal thrombin generation is ~100-200 nM peak
        functional_capacity = iia + xa * 0.5
        normal_capacity = 150.0  # nM reference

        if functional_capacity < 1e-6:
            # No coagulation capacity -> very high INR
            return 10.0

        pt_ratio = normal_capacity / (functional_capacity + 1e-6)
        pt_ratio = np.clip(pt_ratio, 0.5, 10.0)
        inr = pt_ratio ** p["isi"]
        return float(np.clip(inr, 0.8, 10.0))

    def get_aptt(self, state: np.ndarray) -> float:
        """Calculate aPTT from the current coagulation state.

        aPTT reflects intrinsic pathway function, modeled as inversely related
        to the available factor activity and thrombin generation.
        """
        p = self.params
        iia = max(state[3], 0.0)
        xa = max(state[1], 0.0)
        at3_bound = max(state[6], 0.0)

        # More AT-III binding means less available factors -> longer aPTT
        inhibition_factor = 1.0 + at3_bound / (p["at3_total"] * 0.1)

        # Less thrombin/Xa -> longer aPTT
        activity = (iia + xa) / 200.0  # normalized to ~normal
        activity = max(activity, 0.01)

        aptt = p["normal_aptt_seconds"] * inhibition_factor / activity
        return float(np.clip(aptt, 20.0, 200.0))
