#!/usr/bin/env python3
"""Run the MIMIC-IV heparin PK/PD calibration harness (ISC-7).

This is the Phase-2-collaboration scaffold. It runs *end-to-end* in two
modes:

    # 1) Synthetic mode (no data access required; runs in reproduce.sh)
    python scripts/run_mimic_calibration.py --synthetic

    # 2) Real MIMIC-IV mode (requires a credentialed extract on disk)
    python scripts/run_mimic_calibration.py \\
        --csv /path/to/mimic_heparin_cohort.csv

Outputs (written to `results/` unless `--results-dir` overrides):
    mimic_calibration.json          — fitted params, per-patient RMSE, provenance
    mimic_calibration_report.md     — human-readable Markdown, paper-ready

The report *stamps the data source* in its header so that numbers from a
`--synthetic` run can never be mistaken for MIMIC-IV calibration results.
See `src/hemosim/validation/mimic_schema.md` for the required CSV format
and the SQL sketch that produces it from MIMIC-IV.

Citation for real data: Johnson AEW et al. MIMIC-IV, a freely accessible
electronic health record dataset. Scientific Data 10, 1 (2023).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Allow running as `python scripts/run_mimic_calibration.py` from the
# repo root without installing the package.
_HERE = Path(__file__).resolve()
_SRC = _HERE.parent.parent / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from hemosim.validation.mimic_calibration import (  # noqa: E402
    MIMICHeparinCohort,
    calibrate_heparin_pkpd,
    cohort_summary,
    write_cohort_csv,
)


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "MIMIC-IV heparin PK/PD calibration harness (scaffold). "
            "Runs end-to-end on a synthetic cohort so reproduce.sh can "
            "exercise it; the `--csv` path is the Phase-2 hook for the "
            "real MIMIC-IV extract."
        )
    )
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--csv",
        type=Path,
        default=None,
        help=(
            "Path to a MIMIC-IV heparin cohort CSV (format in "
            "mimic_schema.md). Requires credentialed PhysioNet access."
        ),
    )
    mode.add_argument(
        "--synthetic",
        action="store_true",
        help=(
            "Run on a synthetic cohort generated by "
            "MIMICHeparinCohort.synthetic_cohort. Does NOT require MIMIC "
            "access. Output is clearly stamped `data_source=synthetic`."
        ),
    )
    p.add_argument(
        "--n-patients",
        type=int,
        default=20,
        help="Synthetic-mode cohort size (default 20).",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Seed for synthetic generation and calibration (default 42).",
    )
    p.add_argument(
        "--method",
        choices=("Nelder-Mead", "L-BFGS-B"),
        default="Nelder-Mead",
        help="scipy.optimize.minimize method (default Nelder-Mead).",
    )
    p.add_argument(
        "--max-iter",
        type=int,
        default=400,
        help="Optimizer max iterations (default 400).",
    )
    p.add_argument(
        "--results-dir",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "results",
        help="Output directory (default <repo>/results).",
    )
    p.add_argument(
        "--write-synthetic-csv",
        type=Path,
        default=None,
        help=(
            "Optional: also write the synthetic cohort to this CSV path "
            "so the round-trip is inspectable. Only meaningful with "
            "--synthetic."
        ),
    )
    return p.parse_args()


def main() -> int:
    args = _parse_args()
    results_dir: Path = args.results_dir
    results_dir.mkdir(parents=True, exist_ok=True)

    if args.synthetic:
        print(
            f"[ISC-7] Loading SYNTHETIC MIMIC-shaped cohort "
            f"(n_patients={args.n_patients}, seed={args.seed}) ...",
            flush=True,
        )
        cohort = MIMICHeparinCohort.synthetic_cohort(
            n_patients=args.n_patients, seed=args.seed
        )
        data_source = "synthetic"
        if args.write_synthetic_csv is not None:
            written = write_cohort_csv(cohort, args.write_synthetic_csv)
            print(f"    wrote synthetic CSV to {written}", flush=True)
    else:
        csv_path: Path = args.csv
        if not csv_path.exists():
            print(
                f"[ERROR] CSV not found at {csv_path}. "
                f"See src/hemosim/validation/mimic_schema.md for the "
                f"expected format.",
                file=sys.stderr,
            )
            return 2
        print(
            f"[ISC-7] Loading REAL MIMIC-IV cohort from {csv_path} ...",
            flush=True,
        )
        cohort = MIMICHeparinCohort.from_csv(csv_path)
        data_source = "mimic_iv"

    summary = cohort_summary(cohort)
    print(
        f"    cohort: n_patients={summary['n_patients']} "
        f"n_observations={summary['n_observations']} "
        f"mean_weight_kg={summary['mean_weight_kg']:.1f} "
        f"mean_baseline_aptt={summary['mean_baseline_aptt']:.1f}",
        flush=True,
    )
    if not cohort:
        print(
            "[ERROR] Loaded cohort is empty; cannot calibrate.",
            file=sys.stderr,
        )
        return 3

    print(
        f"[ISC-7] Calibrating HeparinPKPD "
        f"(method={args.method}, max_iter={args.max_iter}) ...",
        flush=True,
    )
    result = calibrate_heparin_pkpd(
        cohort,
        method=args.method,
        max_iter=args.max_iter,
        data_source=data_source,
        seed=args.seed,
    )
    print(
        f"    converged={result.convergence_info['converged']} "
        f"rmse={result.overall_rmse:.3f}s "
        f"nit={result.convergence_info['n_iterations']}",
        flush=True,
    )

    # Write JSON artifact — this is the diffable source of truth.
    json_path = results_dir / "mimic_calibration.json"
    json_payload: dict = {
        "schema_version": "1",
        "data_source": data_source,
        "cohort_summary": summary,
        "calibration": result.to_dict(),
        "cli_args": {
            "csv": str(args.csv) if args.csv else None,
            "synthetic": bool(args.synthetic),
            "n_patients": args.n_patients,
            "seed": args.seed,
            "method": args.method,
            "max_iter": args.max_iter,
        },
    }
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(json_payload, f, indent=2, sort_keys=True)
    print(f"[OK] Wrote {json_path}", flush=True)

    # Write Markdown report — the `markdown_report()` output stamps the
    # data source explicitly, so paper authors can paste this directly.
    md_path = results_dir / "mimic_calibration_report.md"
    md_path.write_text(result.markdown_report(), encoding="utf-8")
    print(f"[OK] Wrote {md_path}", flush=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
